language: node_js
sudo: required

node_js:
  - 10
  - 8

addons:
  firefox: latest
  chrome: stable

env:
  - MOZ_HEADLESS=1

#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start

cache:
  yarn: true
